Criação de uma base simples e funcional para o jogo
giordanorn/soul-eater-game pull request #14
Opened 2019-06-07 00:21 UTC by giordanorn

Inserindo todas as implementações passadas para a branch develop.

2019-06-07 00:24 UTC, JohnVithor approved these changes

2019-06-07 03:39 UTC, jpholanda requested changes
Parece okay. Mas a parte de geração procedural vai ficar pra depois mesmo?

"Requested changes" => na verdade só queria saber isso mesmo antes de aprovar. Infelizmente não sei como editar isso.

2019-06-09 17:36 UTC, giordanorn commented
@jpholanda deixa para um próximo pull request. De agora em diante cada mudança será aprovada a partir de um pull request. Esse pull requeste de agora é só pra poder colocar logo tudo o que já foi feito.

2019-06-09 17:51 UTC, giordanorn commented
Update: Realizei o merge do mapa procedural.

2019-06-09 17:58 UTC, jpholanda commented
Não precisava, já tava aprovando.

2019-06-09 17:59 UTC, jpholanda approved these changes
Aprovado.

2019-06-09 17:59 UTC, merged